//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Extra {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Extra.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert new.
        /// </summary>
        public static string AddNewCollection {
            get {
                return ResourceManager.GetString("AddNewCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input the collection name.
        /// </summary>
        public static string CollectionNamingTitle {
            get {
                return ResourceManager.GetString("CollectionNamingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Collection.
        /// </summary>
        public static string CollectionsTitle {
            get {
                return ResourceManager.GetString("CollectionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Entry.
        /// </summary>
        public static string EntriesTitle {
            get {
                return ResourceManager.GetString("EntriesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input the entry name.
        /// </summary>
        public static string EntryNamingTitle {
            get {
                return ResourceManager.GetString("EntryNamingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input player actions.
        /// </summary>
        public static string InputPlayerActionsTitle {
            get {
                return ResourceManager.GetString("InputPlayerActionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given pattern has the wrong length.
        /// </summary>
        public static string InvalidPatternError {
            get {
                return ResourceManager.GetString("InvalidPatternError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input known pattern information.
        /// </summary>
        public static string KnowledgeInputTitle {
            get {
                return ResourceManager.GetString("KnowledgeInputTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An entry with the given name already exists!.
        /// </summary>
        public static string NameAlreadyExists {
            get {
                return ResourceManager.GetString("NameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Name already exists.
        /// </summary>
        public static string NamingError {
            get {
                return ResourceManager.GetString("NamingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input action results.
        /// </summary>
        public static string RecactinsInputTitle {
            get {
                return ResourceManager.GetString("RecactinsInputTitle", resourceCulture);
            }
        }
    }
}
